package pe.com.claro.eai.ws.postventa.consultaclientecesws.dao;

import pe.com.claro.eai.ws.postventa.consultaclientecesws.bean.*;
import pe.com.claro.eai.ws.postventa.consultaclientecesws.exception.DBException;

public interface SgaDao {

	ConsultarClienteResponse consultarCliente(String mensajeTransaccion, ConsultarClienteRequest objConsultarClienteRequest) throws DBException;
	ConsultarDetalleSucursalResponse consultarDetalleSucursal(String mensajeTransaccion, ConsultarDetalleSucursalRequest objConsultarDetalleSucursalRequest) throws DBException;
	ConsultarEstadoServiciosResponse consultarEstadoServicios(String mensajeTransaccion, ConsultarEstadoServiciosRequest objConsultarEstadoServiciosRequest) throws DBException;
	ConsultarDetalleSucursalDTHResponse consultarDetalleSucursalDTH(String mensajeTransaccion, ConsultarDetalleSucursalDTHRequest objConsultarDetalleSucursalDthRequest) throws DBException;
	ConsultarJanusResponse consultarJanus(String mensajeTransaccion, ConsultarJanusRequest objConsultarJanusRequest) throws DBException;
	RegistrarAuditoriaResponse registrarAuditoria(String mensajeTransaccion, RegistrarAuditoriaRequest objRegistrarAuditoriaRequest) throws DBException;
	ConsultarServicioResponse consultarServicio(String mensajeTransaccion, ConsultarServicioRequest objConsultarServicioRequest) throws DBException;
	ConsultarSeaChangeResponse consultarSeaChange(String mensajeTransaccion, ConsultarSeaChangeRequest objConsultarSeaChangeRequest) throws DBException;
	ConsultarInteraccionCasosResponse consultarSot(String mensajeTransaccion, ConsultarInteraccionCasosRequest objConsultarInteraccionCasosRequest) throws DBException;
	ConsultarInteraccionCasosResponse consultarIncidencia(String mensajeTransaccion, ConsultarInteraccionCasosRequest objConsultarInteraccionCasosRequest) throws DBException;
	ConsultarFallaResponse consultarFalla(String mensajeTransaccion, ConsultarFallaRequest objConsultarFallaRequest) throws DBException;
	ConsultarEquipoResponse consultarEquipoInternet(String mensajeTransaccion, ConsultarEquipoRequest objConsultarEquipoRequest) throws DBException;
	ConsultarEquipoResponse consultarEquipoTelefonia(String mensajeTransaccion, ConsultarEquipoRequest objConsultarEquipoRequest) throws DBException;
	ConsultarEquipoResponse consultarEquipoCable(String mensajeTransaccion, ConsultarEquipoRequest objConsultarEquipoRequest) throws DBException;
	ConsultarEquipoResponse consultarEquipoComplemento(String mensajeTransaccion, ConsultarEquipoRequest objConsultarEquipoRequest) throws DBException;
	ConsultarReglaResponse consultarRegla(String mensajeTransaccion, ConsultarReglaRequest objConsultarReglaRequest) throws DBException;
	ConsultarReglaResponse consultarReglaComplemento(String mensajeTransaccion, ConsultarReglaRequest objConsultarReglaRequest) throws DBException;
	ReconectarNcosResponse reconectarNcos(String mensajeTransaccion, ReconectarNcosRequest objReconectarNcosRequest) throws DBException;
	ConsultarEquipoResponse consultarEquipoLte(String mensajeTransaccion, ConsultarEquipoRequest objConsultarEquipoRequest) throws DBException;
	ConsultarEquipoResponse consultarEquipoComplementoLTEDTH(String mensajeTransaccion, ConsultarEquipoRequest objConsultarEquipoRequest) throws DBException;
	ConsultarServicioSucursalResponse consultarServicioSucursal(String mensajeTransaccion, ConsultarServicioSucursalRequest ConsultarServicioSucursalRequest) throws DBException;
	ConsultarClienteResponse consultarClienteComplemento(String mensajeTransaccion, ConsultarClienteRequest objConsultarClienteRequest) throws DBException;
	String obtenerNumeroDocumento(String mensajeTransaccion, String strCodCli) throws DBException;
	ConsultarClientePorNombreResponse consultarClientePorNombre(String mensajeTransaccion, ConsultarClientePorNombreRequest objConsultarClientePorNombreRequest) throws DBException;
	ConsultarTecnologiaSGAResponse consultarTecnologia(String paramString, ConsultarTecnologiaSGARequest paramConsultarTecnologiaSGARequest) throws DBException;
	ObtenerDatosClienteResponse obtenerDatosCliente(String mensajeTransaccion, String i_codId) throws DBException;
}
