
package pe.com.claro.eai.ws.postventa.consultaclientecesws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "claroFault", targetNamespace = "http://claro.com.pe/eai/ws/postventa/consultaclientecesws/types")
public class ClaroFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private pe.com.claro.eai.ws.postventa.consultaclientecesws.types.ClaroFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ClaroFault(String message, pe.com.claro.eai.ws.postventa.consultaclientecesws.types.ClaroFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ClaroFault(String message, pe.com.claro.eai.ws.postventa.consultaclientecesws.types.ClaroFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: pe.com.claro.eai.ws.postventa.consultaclientecesws.types.ClaroFault
     */
    public pe.com.claro.eai.ws.postventa.consultaclientecesws.types.ClaroFault getFaultInfo() {
        return faultInfo;
    }

}
