
package pe.com.claro.eai.ws.postventa.consultaclientecesws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsultaClienteCESWSService", targetNamespace = "http://claro.com.pe/eai/ws/postventa/consultaclientecesws", wsdlLocation = "/WEB-INF/wsdl/ConsultaClienteCESWS.wsdl")
public class ConsultaClienteCESWSService
    extends Service
{

    private final static URL CONSULTACLIENTECESWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONSULTACLIENTECESWSSERVICE_EXCEPTION;
    private final static QName CONSULTACLIENTECESWSSERVICE_QNAME = new QName("http://claro.com.pe/eai/ws/postventa/consultaclientecesws", "ConsultaClienteCESWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("/WEB-INF/wsdl/ConsultaClienteCESWS.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTACLIENTECESWSSERVICE_WSDL_LOCATION = url;
        CONSULTACLIENTECESWSSERVICE_EXCEPTION = e;
    }

    public ConsultaClienteCESWSService() {
        super(__getWsdlLocation(), CONSULTACLIENTECESWSSERVICE_QNAME);
    }

    public ConsultaClienteCESWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTACLIENTECESWSSERVICE_QNAME, features);
    }

    public ConsultaClienteCESWSService(URL wsdlLocation) {
        super(wsdlLocation, CONSULTACLIENTECESWSSERVICE_QNAME);
    }

    public ConsultaClienteCESWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTACLIENTECESWSSERVICE_QNAME, features);
    }

    public ConsultaClienteCESWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaClienteCESWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsultaClienteCESWSPortType
     */
    @WebEndpoint(name = "ebsconsultaClienteCESSB11")
    public ConsultaClienteCESWSPortType getEbsconsultaClienteCESSB11() {
        return super.getPort(new QName("http://claro.com.pe/eai/ws/postventa/consultaclientecesws", "ebsconsultaClienteCESSB11"), ConsultaClienteCESWSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaClienteCESWSPortType
     */
    @WebEndpoint(name = "ebsconsultaClienteCESSB11")
    public ConsultaClienteCESWSPortType getEbsconsultaClienteCESSB11(WebServiceFeature... features) {
        return super.getPort(new QName("http://claro.com.pe/eai/ws/postventa/consultaclientecesws", "ebsconsultaClienteCESSB11"), ConsultaClienteCESWSPortType.class, features);
    }

    /**
     * 
     * @return
     *     returns ConsultaClienteCESWSPortType
     */
    @WebEndpoint(name = "ebsconsultaClienteCESSB12")
    public ConsultaClienteCESWSPortType getEbsconsultaClienteCESSB12() {
        return super.getPort(new QName("http://claro.com.pe/eai/ws/postventa/consultaclientecesws", "ebsconsultaClienteCESSB12"), ConsultaClienteCESWSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaClienteCESWSPortType
     */
    @WebEndpoint(name = "ebsconsultaClienteCESSB12")
    public ConsultaClienteCESWSPortType getEbsconsultaClienteCESSB12(WebServiceFeature... features) {
        return super.getPort(new QName("http://claro.com.pe/eai/ws/postventa/consultaclientecesws", "ebsconsultaClienteCESSB12"), ConsultaClienteCESWSPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTACLIENTECESWSSERVICE_EXCEPTION!= null) {
            throw CONSULTACLIENTECESWSSERVICE_EXCEPTION;
        }
        return CONSULTACLIENTECESWSSERVICE_WSDL_LOCATION;
    }

}
